# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd9d8a35c071227faf5414d8c1471c53bc1b3fd5fa492755c3dcaa8834111401829d70920f147e7afe700c4c602e58be2d3dbaedb3f33eff1a15b6b42129a6a4

test:
  secret_key_base: 43105d86259f5461ef337c2a679fb602760d4b5aabf46918a3dba64282adccbc6a816ff28c9e015f2b4d65b88e1bdcc61658ec9e4b8f173bd2774db2856eed59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
